# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWbOIQjDVZ-GOaxkBQ7c4_RKFatSLewi
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from PIL import Image

@st.cache_resource
def load_my_model():
    return load_model('mnist_model.h5')

model = load_my_model()

st.title("Handwritten Digit Classifier")
st.write("Upload an image of a handwritten digit (0-9).")

uploaded_file = st.file_uploader("Choose an image...", type=["png", "jpg"])

if uploaded_file is not None:
    try:
        img = Image.open(uploaded_file).convert('L')
        img = img.resize((28, 28))

        st.image(img, caption='Uploaded Image', use_column_width=True)
        st.write("")

        img_array = np.array(img).astype('float32') / 255.0
        img_array = img_array.reshape(1, 784)

        predictions = model.predict(img_array)
        predicted_class = np.argmax(predictions)

        st.success(f"Prediction: {predicted_class}")

    except Exception as e:
        st.error(f"Error: {e}")

